### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by DavidCao22** [DavidCao22/jekyll#1]
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
---
- [x] I am on (or have tested on) ***Windows*** 10+
---

- [ ] Update section on GitHub Pages customer URL?

**Comment by DavidCao22** [comment]
pickup from "creating pages"

**Comment by DavidCao22** [comment]
" The _config.yml master configuration file contains global configurations and variable definitions that are read once at execution time. Changes made to _config.yml during automatic regeneration are not loaded until the next execution.

**Note Data Files are included and reloaded during automatic regeneration. "**
